#! /bin/sh

bspc config border_width        5
bspc config normal_border_color     '#3c3836'
bspc config active_border_color     '#504945'
bspc config focused_border_color    '#7c6f64'
bspc config presel_feedback_color   '#83a598'
bspc config window_gap          20
bspc config top_padding         15

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc cofnig initial_polarity    second_child

#Mouse Control
bspc config pointer_modifier    mod4
bspc config click_to_focus      true


bspc monitor DVI-I-1 -d I II III
bspc monitor DVI-D-0 -d IV V VI

bspc rule -a telegram-desktop state=floating
bspc rule -a google-chrome-beta private=on
bspc rule -a '"MATLAB' state=floating


##Running Scripts/Apps/Tweaks
feh --randomize --bg-fill /shared/Wallpapers &
compton -bcC --backend glx --paint-on-overlay --vsync opengl-swc &
lightsOn 1780 &
urxvtd -q -f -o &
inotify-drives &
redshift &
bar &
