#! /bin/sh
bspc config border_width        5
bspc config normal_border_color     '#3c3836'
bspc config active_border_color     '#689d6a'
bspc config focused_border_color    '#d65d0e'
bspc config presel_feedback_color   '#83a598'
bspc config window_gap          20
bspc config top_padding         15

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config initial_polarity    second_child

#Mouse Control
bspc config pointer_modifier    mod4
bspc config click_to_focus      true

bspc monitor DVI-D-0 -d I II III
#bspc monitor DVI-D-0 -d IV V VI

bspc rule -a telegram-desktop state=pseudo_tiled
bspc rule -a google-chrome-beta private=on
bspc rule -a '"MATLAB' state=floating


##Running Scripts/Apps/Tweaks
feh --randomize --bg-fill /shared/Wallpapers &
compton -cC --backend glx --paint-on-overlay --vsync opengl-swc &
lightsOn 1780 &
inotify-drives &
redshift &
muxic &
sleep 2
bar &
#xsnow -ssnowdepth 30 -wsnowdepth 12 -snowflakes 500 -whirl 7 -notrees -nosanta -norudolf &
